package constants

const (
	REGISTER_CMD = 0
	LOGIN_CMD    = 1

	DEFAULT_PAGE_INDEX = 0
	DEFAULT_PAGE_SIZE  = 10
)
const (
	GET_LIST_PRODUCTS_SUCCESSED int = 0
	GET_LIST_PRODUCTS_FAILED
	GET_PRODUCT_SUCCESSED
	GET_PRODUCT_FAILED
	POST_COMMENT_SUCCESSED
	POST_COMMENT_FAILED
	COMMENT_EMPTY
	GET_COMMENT_SUCCESSED
	GET_COMMENT_FAILED
)
